[package]
name = "simply-simd-macros"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Alysara/simply-simd"
keywords = ["simd", "performance"]
categories = ["game-engines"]
description = "Proc-macros for runtime simd feature detection. Used in the simply-simd crate."
rust-version = "1.95"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3", features = ["full", "visit-mut"] }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "3"
